version: '3'
services:
  portainer:
    image: docker.io/portainer/portainer
    container_name: portainer
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - 9000:9000