#server:
#  port: 8099
logging:
  level:
    root: info
dubbo:
  application:
    name: dubbo-auto-configuration-provider
  # Base packages to scan Dubbo Component: @org.apache.dubbo.config.annotation.Service
  scan:
    base-packages: com.dubbo.provider.service
  protocol:
    name: dubbo
    port: 12345
  registry:
    address: zookeeper://localhost:12181

